spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/internship_interview_appointment
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
admin:
  username: teacher
  password: password
jwt:
  key: key