spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5432/internship_interview_appointment
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect